Booking.destroy_all
Politician.destroy_all
User.destroy_all

a = User.create!(email: "bobusa@gmail.com", password: "password")
b = User.create(email: "aliceeu@gmail.com", password: "password")
c = User.create(email: "frankworld@gmail.com", password: "password")

d = User.create(email: "derekright@gmail.com", password: "password")
e = User.create(email: "enzoleft@gmail.com", password: "password")

p1 = Politician.create!( name: 'Barack Obama', location: "USA", cost: 100, description: "Barack Hussein Obama II [a]  (born August 4, 1961) is an American politician who served as the 44th  president of the United States  from 2009 to 2017. A member of the  Democratic Party , he was the first  African-American president  in United States history. Obama previously served as a U.S. senator representing Illinois from 2005 to 2008, as an  Illinois state senator  from 1997 to 2004, and as a community service organizer, civil rights  lawyer, and university lecturer. ", image_url:"https://ygo-assets-entities-us.yougov.net/516e6836-d278-11ea-a709-979a0378f022.jpg?pw=7000", user_id: a.id )
p2 = Politician.create!( name: 'George W. Bush', location: "USA", cost: 200, description: "George Walker Bush  (born July 6, 1946) is an American politician and businessman who served  as the 43rd  president of the United States  from 2001 to 2009. A member of the  Republican Party , he previously served as the 46th  governor of Texas  from 1995 to 2000. ", image_url:"https://ygo-assets-entities-us.yougov.net/af46ff95-738d-11ea-affe-f9053ded7ac4.jpg?pw=7000", user_id: a.id )
p3 = Politician.create!( name: 'Joe Biden', location: "USA", cost: 300, description: "Joseph Robinette Biden Jr.  ( /ˈbaɪdən/ⓘ BY-dən ; born November 20, 1942) is an American politician who is the 46th and current  president of the United States  since 2021. A member of the  Democratic Party , he previously served as the 47th  vice president  from 2009 to 2017 under President  Barack Obama  and represented  Delaware  in the  United States Senate  from 1973 to 2009. ", image_url:"https://ygo-assets-entities-us.yougov.net/67a5222a-5c70-11eb-8d48-eb9b21d67bdc.jpg?pw=7000", user_id: a.id )
p4 = Politician.create!( name: 'Hillary Clinton', location: "USA", cost: 400, description: "Hillary Diane Rodham Clinton  ( née Rodham ; born October 26, 1947) is an American politician and diplomat who served  as the 67th  United States secretary of state  in the administration of  Barack Obama  from 2009 to 2013, as a  U.S. senator  representing New York from 2001 to 2009, and as the  first lady of the U.S.  to president  Bill Clinton  from 1993 to 2001. A member of the  Democratic Party , she was the party's nominee in the  2016 U.S. presidential election , becoming the first woman to win a presidential nomination by a major U.S.  political party and the first woman to win the popular vote for U.S.  president. ", image_url:"https://ygo-assets-entities-us.yougov.net/8f2b363a-4413-11e6-90f5-85880927bf80.jpg?pw=7000", user_id: a.id )
p5 = Politician.create!( name: 'Arnold Schwarzenegger', location: "USA", cost: 500, description: "Arnold Alois Schwarzenegger  (born July 30, 1947) is an Austrian and American actor, businessman, filmmaker, former politician, and former professional bodybuilder known for his roles in high-profile action movies. He  served  as the  38th governor of California  from 2003 to 2011 and was among  Time's 100 most influential people in the world  in 2004 and 2007. [5] [6]", image_url:"https://ygo-assets-entities-us.yougov.net/a58e390d-2d00-11e6-9dc6-455dca91e85a.jpg?pw=7000", user_id: a.id )
p6 = Politician.create!( name: 'Donald Trump', location: "USA", cost: 600, description: "Donald John Trump  (born June 14, 1946) is an American politician, media personality, and  businessman who served as the 45th  president of the United States  from 2017 to 2021. ", image_url:"https://ygo-assets-entities-us.yougov.net/ddb8156b-fee8-11ed-9d53-6515ccbf4e2f.jpg?zcw=655&zch=655&zct=40&zcl=97&pw=7000", user_id: a.id )
p7 = Politician.create!( name: 'Bernie Sanders', location: "USA", cost: 700, description: "Bernard Sanders  (born September 8, 1941) is an American politician and activist who is the  senior United States senator  from  Vermont . Sanders is the longest-serving  independent  in U.S. congressional history but has a close relationship with the  Democratic Party , having  caucused  with  House  and  Senate Democrats  for most of his congressional career and sought the party's  presidential  nomination in  2016  and  2020 , coming second in both campaigns. He is often seen as a leader of the  U.S. progressive movement", image_url:"https://ygo-assets-entities-us.yougov.net/d37b9602-098d-11e7-bbcc-8b355fa30afe.jpg?pw=7000", user_id: a.id )
p8 = Politician.create!( name: 'Kamala Harris', location: "USA", cost: 800, description: "Kamala Devi Harris [a]  ( /ˈkɑːmələ ˈdeɪvi/ⓘ KAH-mə-lə DAY-vee ; [2] [3]  born October 20, 1964) is an American politician and attorney who is the  49th and current  vice president of the United States  under President  Joe Biden . She is the first female vice president and the highest-ranking female  official in U.S. history, as well as the first  African-American  and first  Asian-American  vice president. [4] [5]  A member of the  Democratic Party , she was previously  attorney general of California  from 2011 to 2017 and a  U.S. senator  from  California  from 2017 to 2021. ", image_url:"https://ygo-assets-entities-us.yougov.net/8074de4c-5c6f-11eb-ba60-1dea87cb8f5c.jpg?pw=7000", user_id: a.id )
p9 = Politician.create!( name: 'Jimmy Carter', location: "USA", cost: 900, description: "James Earl Carter Jr.  (born October 1, 1924) is an American politician and humanitarian who served as the 39th  president of the United States  from 1977 to 1981. A member of the  Democratic Party , Carter was the 76th  governor of Georgia  from 1971 to 1975, and a  Georgia state senator  from 1963 to 1967. At age 99, he is both the oldest living former U.S. president and the  longest-lived president in U.S. history . ", image_url:"https://ygo-assets-entities-us.yougov.net/af35e885-738d-11ea-affe-f9053ded7ac4.jpg?pw=7000", user_id: a.id )
p10 = Politician.create!( name: 'Nancy Pelosi', location: "USA", cost: 1000, description: "Nancy Patricia Pelosi  ( /pəˈloʊsi/ pə-LOH-see ;  néeD'Alesandro ; born March 26, 1940) is an American politician who served as the  52nd speaker of the United States House of Representatives  from 2007 to 2011 and again from 2019 to 2023. A member of the  Democratic Party , she was the first woman elected as U.S. House Speaker and the first woman to lead a major political party in either chamber of  Congress , leading the  House Democrats  from 2003 to 2023. A member of the House since 1987, Pelosi currently represents  California's 11th congressional district , which includes most of  San Francisco . She is the dean of  California's congressional delegation . ", image_url:"https://ygo-assets-entities-us.yougov.net/99d4b1a5-0781-11ea-923c-e3a824502dfc.jpg?zcw=773&zch=773&zct=0&zcl=0&pw=7000", user_id: a.id )
p11 = Politician.create!( name: 'Bill Clinton', location: "USA", cost: 1100, description: "William Jefferson Clinton  ( né Blythe III ; born August 19, 1946) is an American politician who served as the 42nd  president of the United States  from 1993 to 2001. A member of the  Democratic Party , he previously served as  governor of Arkansas  from 1979 to 1981 and again from 1983 to 1992. Clinton, whose policies reflected a centrist "" Third Way "" political philosophy, became known as a  New Democrat . ", image_url:"https://ygo-assets-entities-us.yougov.net/a271d882-c63b-11e8-b786-f96307b120ad.jpg?zcw=629&zch=629&zct=0&zcl=264&pw=7000", user_id: a.id )
p12 = Politician.create!( name: 'Robert F. Kennedy, Jr.', location: "USA", cost: 1200, description: "Robert Francis Kennedy Jr.  (born January 17, 1954), also known by his initials  RFK Jr. , is an American politician,  environmental lawyer ,  anti-vaccine activist , and  conspiracy theorist . He is the chairman and founder of  Children's Health Defense , an anti-vaccine advocacy group that is a leading proponent of COVID-19 vaccine misinformation, [1] [2]  and an independent  candidate  in the  2024 presidential election . A member of the  Kennedy family , he is a son of  U.S. attorney general  and senator  Robert F. Kennedy , and nephew of U.S. president  John F. Kennedy  and senator  Ted Kennedy", image_url:"https://ygo-assets-entities-us.yougov.net/63ce3711-84c0-11ee-8819-5bdc555e4eaf.jpg?pw=7000", user_id: a.id )
p13 = Politician.create!( name: 'Sarah Palin', location: "USA", cost: 1300, description: "Sarah Louise Palin  ( /ˈpeɪlɪn/ⓘ ;  née Heath ; born February 11, 1964) is an American politician, commentator, author, and reality television personality who served as the ninth  governor of Alaska  from 2006 until  her resignation  in 2009. She was the  2008 Republican vice presidential nominee  alongside  U.S. Senator John McCain . ", image_url:"https://ygo-assets-entities-us.yougov.net/ba67b401-2d0a-11e6-bce7-6ff134176666.jpg?pw=7000", user_id: a.id )
p14 = Politician.create!( name: 'Mike Pence', location: "USA", cost: 1400, description: "Michael Richard Pence  (born June 7, 1959) is an American politician who served as the 48th  vice president of the United States  from 2017 to 2021 under President  Donald Trump . A member of the  Republican Party , he previously served as the 50th  governor of Indiana  from 2013 to 2017, and a member of the  U.S. House of Representatives  from 2001 to 2013. ", image_url:"https://ygo-assets-entities-us.yougov.net/42348fa5-3ef5-11e7-bd17-7780b36eac03.jpg?pw=7000", user_id: a.id )
p15 = Politician.create!( name: 'Dick Cheney', location: "USA", cost: 1500, description: "Richard Bruce Cheney  ( /ˈtʃeɪni/ CHAY-nee ; [a]  born January 30, 1941) is an American retired politician and businessman who served as the 46th  vice president of the United States  from 2001 to 2009 under President  George W. Bush . Often cited as the most powerful vice president in American history, [4] [5]  Cheney previously served as  White House Chief of Staff  for President  Gerald Ford , the  U.S. representative  for  Wyoming's at-large congressional district  from 1979 to 1989, and as the 17th  United States secretary of defense  in the administration of President  George H. W. Bush . He is the oldest living former U.S. vice president, following the death  of  Walter Mondale  in 2021. ", image_url:"https://ygo-assets-entities-us.yougov.net/1e08e514-2d03-11e6-9570-cf1c514d3e57.jpg?pw=7000", user_id: a.id )
p16 = Politician.create!( name: 'Mitt Romney', location: "USA", cost: 1600, description: "Willard Mitt Romney  (born March 12, 1947) is an American politician, businessman, and lawyer who has served as the  junior United States senator  from  Utah  since 2019. He served as the 70th  governor of Massachusetts  from 2003 to 2007 and was the  Republican Party s nominee for  president of the United States  in the  2012 election , losing to  Barack Obama . ", image_url:"https://ygo-assets-entities-us.yougov.net/442ce5c4-2d08-11e6-a4bd-71dbf5f2854a.jpg?pw=7000", user_id: a.id )
p17 = Politician.create!( name: 'Ted Cruz', location: "USA", cost: 1700, description: "Rafael Edward Cruz  ( /kruːz/ ; born December 22, 1970) is an American politician, attorney, and political commentator serving as the  junior United States senator  from  Texas  since 2013. A member of the  Republican Party , Cruz was the  solicitor general of Texas  from 2003 to 2008. ", image_url:"https://ygo-assets-entities-us.yougov.net/eab6136d-2d0b-11e6-8fa2-87887d182df9.jpg?pw=7000", user_id: a.id )
p21 = Politician.create!( name: 'Vladimir Putin', location: "Russia", cost: 100, description: "Vladimir Vladimirovich Putin [c] [d]  (born 7 October 1952) is a Russian politician and former intelligence officer who is the  president of Russia . Putin has  held continuous positions  as president or  prime minister  since 1999: [e]  as prime minister from 1999 to 2000 and from 2008 to 2012, and as president from 2000 to 2008 and since 2012. [f] [7]  He is the longest-serving Russian or Soviet leader since  Joseph Stalin . ", image_url: "	https://ygo-assets-entities-us.yougov.net/cdac6230…5dca91e85a.jpg?zcw=218&zch=218&zct=6&zcl=28&pw=7000", user_id: b.id )
p22 = Politician.create!( name: 'Justin Trudeau', location: "Canada", cost: 200, description: "Justin Pierre James Trudeau PCMP  ( /ˈtruːdoʊ, truːˈdoʊ/ⓘ TROO-doh, troo-DOH) French: [ʒystɛ̃ pjɛʁ dʒɛms tʁydo] ; born December 25, 1971) is a Canadian politician who has served as the 23rd  prime minister of Canada  since 2015 and the leader of the  Liberal Party  since 2013. Trudeau was the second-youngest  prime minister in Canadian history  when he took office and the first to be the child of a previous holder of the post, as the eldest son of  Pierre Trudeau . ", image_url: "https://ygo-assets-entities-us.yougov.net/951c1caf-2d06-11e6-8fa2-87887d182df9.jpg?pw=7000", user_id: b.id )
p23 = Politician.create!( name: 'Tony Blair', location: "UK", cost: 300, description: "Sir Anthony Charles Lynton Blair KG  (born 6 May 1953) is a British politician who served as  Prime Minister of the United Kingdom  from 1997 to 2007 and  Leader of the Labour Party  from 1994 to 2007. He served as  Leader of the Opposition  from 1994 to 1997 and held various  shadow cabinet  posts from 1987 to 1994. Blair was  Member of Parliament  (MP) for  Sedgefield  from 1983 to 2007. He is the second- longest-serving prime minister  in post-war British history (after  Margaret Thatcher ) and the longest-serving  Labour  politician to have held the office. ", image_url: "https://ygo-assets-entities-us.yougov.net/310c8ea7-2d0d-11e6-a4bd-71dbf5f2854a.jpg?pw=7000", user_id: b.id )
p24 = Politician.create!( name: 'Volodymyr Zelenskyy', location: "Ukraine", cost: 400, description: "Volodymyr Oleksandrovych Zelenskyy [a] [b] [c]  (born 25 January 1978) is a Ukrainian politician and former actor who has been serving as the sixth  president of Ukraine  since 2019. ", image_url: "https://ygo-assets-entities-us.yougov.net/f1c76dc2-9a2c-11ec-9686-0915ce2c2d35.jpg?zcw=259&zch=259&zct=0&zcl=114&pw=140", user_id: b.id )
p25 = Politician.create!( name: 'Boris Johnson', location: "UK", cost: 500, description: "Alexander Boris de Pfeffel Johnson  (born 19 June 1964) is a British politician and writer who was  Prime Minister of the United Kingdom  and  Leader of the Conservative Party  from 2019 to 2022. He was previously  Foreign Secretary  from 2016 to 2018 and  Mayor of London  from 2008 to 2016. He was  Member of Parliament  (MP) for  Henley  from 2001 to 2008 and  Uxbridge and South Ruislip  from 2015 to 2023. ", image_url: "https://ygo-assets-entities-us.yougov.net/862f85a5-bfb1-11eb-a27f-f791d9338693.jpg?pw=140", user_id: b.id )
p26 = Politician.create!( name: 'Angela Merkel', location: "Germany", cost: 600, description: "Angela Dorothea Merkel German: [aŋˈɡeːla doʁoˈteːa ˈmɛʁkl̩] ⓘ ; [a] néeKasner ; born 17 July 1954) is a German retired politician and chemist who served as  Chancellor of Germany  from 2005 to 2021 and was the first woman to hold that office. She previously served as  Leader of the Opposition  from 2002 to 2005 and as  Leader of the Christian Democratic Union  from 2000 to 2018. [9]  During her chancellorship, Merkel was frequently referred to as the  de facto  leader of the  European Union  (EU) and the most powerful woman in the world. Beginning in  2016 , she was often described as the  leader of the free world . [10]", image_url: "https://ygo-assets-entities-us.yougov.net/ef0b5614-b0b7-11e6-adde-09142178952f.jpg?pw=140", user_id: b.id )
p27 = Politician.create!( name: 'Xi Jinping', location: "Taiwan", cost: 700, description: "The son of Chinese Communist veteran  Xi Zhongxun , Xi was exiled to rural  Yanchuan County  as a teenager following his father's purge during the  Cultural Revolution . He lived in a  yaodong  in the village of Liangjiahe,  Shaanxi province , where he joined the CCP after several failed attempts and worked as the local  party secretary . After studying  chemical engineering  at  Tsinghua University  as a  worker-peasant-soldier student , Xi rose through the ranks politically in China's coastal provinces. Xi was  governor of Fujian  from 1999 to 2002, before becoming governor and party secretary of neighboring  Zhejiang  from 2002 to 2007. Following the dismissal of the party secretary of Shanghai,  Chen Liangyu , Xi was transferred to replace him for a brief period in 2007. He subsequently joined the  Politburo Standing Committee  (PSC) of the CCP the same year and was the first-ranking secretary of the  Central Secretariat", image_url: "https://ygo-assets-entities-us.yougov.net/5e378ea6-2d0e-11e6-9570-cf1c514d3e57.jpg?pw=140", user_id: c.id )
p28 = Politician.create!( name: 'Emmanuel Macron', location: "France", cost: 800, description: "Emmanuel Jean-Michel Frédéric Macron French: [emanɥɛl makʁɔ̃] ; born 21 December 1977) is a French politician who has been  President of France  since 2017. Macron is  ex officio  one of the two  Co-Princes of Andorra . He previously was  Minister of Economics, Industry and Digital Affairs  under President  François Hollande  from 2014 to 2016 and Deputy Secretary-General to the President from 2012 to 2014. He is a founding member of  Renaissance , a centrist political party.", image_url: "https://ygo-assets-entities-us.yougov.net/5e5f935c-d0c7-11e6-8d77-97af53817351.jpg?pw=140", user_id: b.id )
p29 = Politician.create!( name: 'David Cameron', location: "UK", cost: 900, description: "David William Donald Cameron, Baron Cameron of Chipping Norton ,  PC  (born 9 October 1966) is a British politician who has served as  Foreign Secretary  since 2023. He previously served as  Prime Minister of the United Kingdom  from 2010 to 2016, as  Leader of the Conservative Party  from 2005 to 2016, and as  Leader of the Opposition  from 2005 to 2010, while serving as  Member of Parliament  (MP) for  Witney  from 2001 to 2016. He identifies as a  one-nation conservative  and has been associated with both  economically liberal  and  socially liberal  policies. ", image_url: "https://ygo-assets-entities-us.yougov.net/9fbb0a31-c63d-11e8-8e97-49c7134d7a4e.jpg?zcw=942&zch=942&zct=32&zcl=1&pw=140", user_id: b.id )
p210 = Politician.create!( name: 'Mohammed bin Salman', location: "Saudi Arabia", cost: 1000, description: "Mohammed bin Salman Al Saud  ( Arabic :  محمد بن سلمان آل سعود ,  romanized:  Muḥammad bin Salmān ʾĀl Su‘ūd ; born 31 August 1985) is the  de facto  ruler of Saudi Arabia. The  heir apparent  to the  Saudi Arabian throne , he is currently  Crown Prince  and  Prime Minister . He is the seventh son of  King Salman of Saudi Arabia  and grandson of the nation's founder,  King Abdulaziz .", image_url: "https://ygo-assets-entities-us.yougov.net/568a26d2-1fa5-11e9-b579-ad83f130f935.jpg?zcw=561&zch=561&zct=0&zcl=244&pw=140", user_id: c.id )
p211 = Politician.create!( name: 'Theresa May', location: "UK", cost: 1100, description: "Theresa Mary, Lady May  ( /təˈriːzə/ ; [1] néeBrasier ; born 1 October 1956) is a British politician who served as  Prime Minister of the United Kingdom  and  Leader of the Conservative Party  from 2016 to 2019. She previously served as  Home Secretary  from 2010 to 2016. She has been  Member of Parliament  (MP) for  Maidenhead  since 1997. May is the second female UK prime minister, after  Margaret Thatcher , and the first woman to hold two of the  Great Offices of State . Ideologically, May is a  one-nation conservative . [2]", image_url: "https://ygo-assets-entities-us.yougov.net/eda4fa12-4d1a-11e7-8dd6-1d2e5f5adde4.jpg?pw=140", user_id: b.id )
p212 = Politician.create!( name: 'Salman bin Abdulaziz Al Saud', location: "Saudi Arabia", cost: 1200, description: "Salman bin Abdulaziz Al Saud  ( Arabic :  سلمان بن عبد العزیز آل سعود ,  romanized:  Salmān bin ʿAbd al-ʿAzīz Āl Su‘ūd ; born 31 December 1935) is  King of Saudi Arabia , reigning since 2015, and was also  Prime Minister of Saudi Arabia  from 2015 to 2022. The 25th son of  King Abdulaziz , the founder of  Saudi Arabia , he assumed the throne on 23 January 2015. Prior to his accession, he was  Crown Prince of Saudi Arabia  from 18 June 2012 to 23 January 2015. Salman is the  third oldest living head of state , the oldest living monarch, and Saudi Arabia's first head of state born after the  unification of Saudi Arabia . He has a reported personal wealth of at least $18 billion, which makes him the third wealthiest royal in the world and one of the wealthiest individuals in the world. [1]", image_url: "https://ygo-assets-entities-us.yougov.net/1ae39d1a-1fa5-11e9-aa2b-edabeda724d3.jpg?zcw=1807&zch=1807&zct=0&zcl=311&pw=140", user_id: c.id )
p213 = Politician.create!( name: 'Nicolás Maduro', location: "Venezuela", cost: 1300, description: "Nicolás Maduro Moros Spanish: [nikoˈlas maˈðuɾo ˈmoɾos] ⓘ ; born 23 November 1962) is a Venezuelan politician who has served as the  president of Venezuela  since  2013 . ", image_url: "https://ygo-assets-entities-us.yougov.net/1272c65d-1fa4-11e9-b579-ad83f130f935.jpg?zcw=405&zch=405&zct=2&zcl=156&pw=140", user_id: c.id )
p214 = Politician.create!( name: 'Recep Tayyip Erdoğan', location: "Turkey", cost: 1400, description: "Recep Tayyip Erdoğan [b]  (born 26 February 1954) is a Turkish politician who is the 12th and current  president of Turkey . He previously served as  prime minister  from 2003 to 2014 as part of the  Justice and Development Party  (AKP), which he co-founded in 2001. He also served as  mayor of Istanbul  from 1994 to 1998. ", image_url: "https://ygo-assets-entities-us.yougov.net/9eb16822-5304-11e6-b0b4-eb60285ecf02.jpg?pw=140", user_id: b.id )
p215 = Politician.create!( name: 'Shinzō Abe', location: "Japan", cost: 1500, description: "Shinzo Abe  ( /ˈʃɪnzoʊ ˈɑːbeɪ/ SHIN-zoh AH-bay ;  Japanese :  安倍 晋三 ,  Hepburn :  Abe Shinzō ,  [abe ɕindzoː] ; 21 September 1954 – 8 July 2022) was a Japanese politician and statesman  who served as  Prime Minister of Japan  and  President of the Liberal Democratic Party  (LDP) from 2006 to 2007 and again from 2012 to 2020. He was the  longest-serving prime minister  in Japanese history, serving for almost nine years in total. Abe also served as  Chief Cabinet Secretary  from 2005 to 2006 under  Junichiro Koizumi  and was briefly the opposition leader in 2012. ", image_url: "https://ygo-assets-entities-us.yougov.net/15c478b9-3757-11e8-9e7e-d1937979c38e.jpg?zcw=220&zch=220&zct=0&zcl=0&pw=140", user_id: c.id )
p216 = Politician.create!( name: 'Narendra Modi', location: "India", cost: 1600, description: "Narendra Damodardas Modi Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ ; born 17 September 1950) [b]  is an Indian politician who has served as the 14th  prime minister of India  since May 2014. Modi was the  chief minister of Gujarat  from 2001 to 2014 and is the  Member of Parliament  (MP) for  Varanasi . He is a member of the  Bharatiya Janata Party  (BJP) and of the  Rashtriya Swayamsevak Sangh  (RSS), a  right wing Hindu nationalist  paramilitary volunteer organisation. He is the longest-serving prime minister from outside the  Indian National Congress . ", image_url: "https://ygo-assets-entities-us.yougov.net/e697fd2c-c7ad-11e8-8d12-4b6fc186e574.jpg?zcw=450&zch=450&zct=0&zcl=0&pw=140", user_id: c.id )
p217 = Politician.create!( name: 'Jair Bolsonaro', location: "Brazil", cost: 1700, description: "Jair Messias Bolsonaro Brazilian Portuguese: [ʒaˈiʁ meˈsi.ɐz bowsoˈnaɾu] ; born 21 March 1955) is a Brazilian politician and retired military officer who served as the 38th  president of Brazil  from 2019 to 2023. He previously served as member of Brazil's  Chamber of Deputies  from 1991 to 2018. ", image_url: "https://ygo-assets-entities-us.yougov.net/d3855ca0-cd6a-11e8-a722-affcf7e3f830.jpg?pw=140", user_id: c.id )
p218 = Politician.create!( name: 'Gordon Brown', location: "UK", cost: 1800, description: "James Gordon Brown HonFRSE  (born 20 February 1951) is a British politician who served as  Prime Minister of the United Kingdom  and  Leader of the Labour Party  from 2007 to 2010. He previously served as  Chancellor of the Exchequer  under  Tony Blair  from 1997 to 2007. He was  Member of Parliament  (MP) for  Dunfermline East  from 1983 to 2005, and  Kirkcaldy and Cowdenbeath  from 2005 to 2015. Brown is the most recent  Labour Party  prime minister and the most recent not to be from England. ", image_url: "https://ygo-assets-entities-us.yougov.net/e6d8fff6-14c3-11e9-9e9a-63247b032ab8.jpg?zcw=387&zch=387&zct=0&zcl=117&pw=140", user_id: b.id )
p219 = Politician.create!( name: 'Enrique Peña Nieto', location: "Mexico", cost: 1900, description: "Enrique Peña Nieto OMRICYCGCB Spanish pronunciation: [enˈrike ˈpeɲa ˈnjeto] ⓘ ; born 20 July 1966), commonly referred to by his initials  EPN , is a Mexican former politician who served as the 64th  president of Mexico  from 2012 to 2018. A member of the  Institutional Revolutionary Party  (PRI), he previously served as  Governor of the State of Mexico  from 2005 to 2011,  local deputy  from 2003 to 2004, and  Secretary of Administration  from 2000 to 2002. ", image_url: "https://ygo-assets-entities-us.yougov.net/43a131da-3757-11e8-a175-dfc2b12b020e.jpg?pw=140", user_id: c.id )
p220 = Politician.create!( name: 'Antonio Guterres', location: "World", cost: 1900, description: "António Manuel de Oliveira Guterres GCCGCL  ( /ɡʊˈtɛrəs/ⓘ , European Portuguese: [ɐ̃ˈtɔnju ɣuˈtɛʁɨʃ] ⓘ ; born 30 April 1949) [1]  is a Portuguese politician and diplomat. Since 2017, he has served as  secretary-general of the United Nations , the ninth person to hold this title. A member of the  Portuguese Socialist Party , Guterres served as  prime minister of Portugal  from 1995 to 2002. ", image_url: "https://ygo-assets-entities-us.yougov.net/d88cd25d-91e3-11e6-bce9-1b81e7850bd7.jpg?pw=140", user_id: c.id )


politicians = [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p21, p22, p23, p24, p25, p26, p27, p28, p29, p210, p211, p212, p213, p214, p215, p216, p217, p218, p219, p219, p220]

Booking.create!(politician_id: politicians.sample.id, user_id: d.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: d.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: d.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: d.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: e.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: e.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: e.id, status: 0)
Booking.create(politician_id:  politicians.sample.id, user_id: e.id, status: 0)

p "users: #{User.count}"
p "polis: #{Politician.count}"
p "bookings: #{Booking.count}"

p "seed done 😊"
